# Generated by Django 2.1.3 on 2019-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracaos', '0001_initial'),
        ('core', '0002_auto_20190522_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(to='atracaos.Atracao'),
        ),
    ]
